### ISSUE TITLE
Too few trades mismatch

### ISSUE THREAD

**Issue by BurkenDev** [Ordwen/ODailyQuests#54]
I noted a weird issue, I've traded way more than 64 bread with a villager which I set my quest to be.
Yet the plugin only detects 18 trades.

![image](https://github.com/Ordwen/ODailyQuests/assets/72360068/fcd9711a-275f-4394-8dd7-941619aa8936)

Quest config:

```
    name: "&8&l[#5bba5d&l?&8&l] &7Villager Contract: &eBread"
    menu_item: PAPER
    description:
      - "&e"
      - "#5bba5d&lOBJECTIVE: &7Trade 64 Bread from a Villager"  
      - "&e"
      - "#5bba5d&lREWARD: &7$750"
    quest_type: VILLAGER_TRADE
    required_item: BREAD
    required_amount: 64
    reward:
      reward_type: MONEY
      amount: 750

```
This seems to be pretty strange to me.
