### ISSUE TITLE
Item checks are strict.

### ISSUE THREAD

**Issue by NamiUni** [Ordwen/ODailyQuests#7]
The item check process needs to be changed.

Right now the item checks are too strict and could make some quests impossible to progress.
Example: the Tropical Fish Bucket always adds an NBT tag when in survival mode, so the following quests are not progressible.
```yaml
quests:
  1:
    name: "Scuba Diving"
    required_item: TROPICAL_FISH_BUCKET
    required_amount: 1
```

The bug is caused by the following code.
https://github.com/Ordwen/ODailyQuests/blob/46c122e9d1f57699baa3ffaeb7cc9891f22c1a36/src/main/java/com/ordwen/odailyquests/quests/player/progression/checkers/AbstractSpecifiedChecker.java#L44

Need to change the checking method between custom item checks and regular item checks.
